(function () {
  "use strict";
  window.LYRICS = [
    { t: 1.05, line: "Okey..." },
    { t: 2.21, line: "Giros, todo da vueltas como una gran pelota" },
    { t: 6.93, line: "Todo da vueltas casi ni se nota" },
    { t: 10.59, line: "" },
    { t: 30.46, line: "Hoy me encontré" },
    { t: 32.26, line: "Dama magistral" },
    { t: 34.74, line: "Sus puertas del Edén" },
    { t: 36.94, line: "Son el caminito pa' recorrer" },
    { t: 41.29, line: "Con alas la eternidad" },
    { t: 43.53, line: "Haceme el amor como animal" },
    { t: 47.97, line: "Respiro de a dos" },
    { t: 49.89, line: "Hay un paraíso en tu corazón" },
    { t: 54.21, line: "Tu risa me guiará" },
    { t: 56.77, line: "Yo sé del mal en tu canción" },
    { t: 60.85, line: "Tus venas con sal" },
    { t: 62.57, line: "Y aunque el diablo blanco te consumió" },
    { t: 67.13, line: "Te quiero ver ser" },
    { t: 69.33, line: "En tus brazos siempre en tus brazos" },
    { t: 72.29, line: "En tus brazos siempre en tus brazos" },
    { t: 75.77, line: "En tus brazos siempre en tus brazos" },
    { t: 78.97, line: "En tus brazos siempre en tus brazos" },
    { t: 81.98, line: "" },
    { t: 95.58, line: "Incertidumbre y vanidad" },
    { t: 99.90, line: "Suerte y seducción" },
    { t: 101.74, line: "Soy tan vulnerable si te volteas" },
    { t: 106.22, line: "Amor amores" },
    { t: 108.18, line: "Estás incognitando mi cantar" },
    { t: 112.81, line: "Y aún no somos dos" },
    { t: 114.65, line: "Entre el bien y el mal hay una oración" },
    { t: 119.09, line: "Y dos pasos para atrás" },
    { t: 121.61, line: "Desde hace cuánto no sale el sol" },
    { t: 127.77, line: "Sé que el diablo blanco te consumió" },
    { t: 131.73, line: "Pero te quiero ver ser" },
    { t: 134.09, line: "En tus brazos siento aquella flor marchitada de un jacarandá" },
    { t: 140.65, line: "Sos la diosa ama de mi sol" },
    { t: 143.89, line: "Que me brinda luz en la oscuridad" },
    { t: 147.21, line: "En tus brazos siempre en tus brazos" },
    { t: 150.57, line: "En tus brazos siempre en tus brazos" },
    { t: 154.01, line: "En tus brazos siempre en tus brazos" },
    { t: 157.41, line: "En tus brazos siempre en tus brazos" },
    { t: 160.89, line: "En tus brazos siento aquella flor marchitada de un jacarandá" },
    { t: 167.77, line: "Sos la diosa ama de mi sol" },
    { t: 171.17, line: "Que me brinda luz en la oscuridad" },
    { t: 174.41, line: "" }
  ];
})();