(function () {
  "use strict";
  window.LYRICS = [
    { t: 0.0, line: "Okey..." },
    { t: 5.0, line: "Giros, todo da vueltas como una gran pelota" },
    { t: 11.0, line: "Todo da vueltas, casi ni se nota" },
    { t: 16.0, line: "Ta-ra-ra, ta-ra-ra" },
    { t: 20.0, line: "Ta-ra-ra-ra-rai" },
    { t: 24.0, line: "Uh-uh, uh-uh, uh" },
    { t: 27.0, line: "Ay-ay-ay-ay-ay-ay" },
    { t: 31.0, line: "Uh-uh, uh-uh" },
    { t: 35.0, line: "Hoy me encontré, dama magistral" },
    { t: 40.0, line: "Sus puertas del Edén son el caminito pa' recorrer" },
    { t: 46.5, line: "Con alas la eternidad" },
    { t: 51.0, line: "Haceme el amor como animal, respiro de a dos" },
    { t: 57.0, line: "Hay un paraíso en tu corazón, tu risa me guiará" },
    { t: 62.5, line: "Yo sé del mal en tu canción" },
    { t: 67.0, line: "Tus venas con sal" },
    { t: 71.0, line: "Y aunque el diablo blanco te consumió" },
    { t: 76.0, line: "Te quiero ver ser" },
    { t: 80.0, line: "En tus brazos, siempre en tus brazos" },
    { t: 85.0, line: "En tus brazos, siempre en tus brazos" },
    { t: 90.0, line: "En tus brazos, siempre en tus brazos" },
    { t: 95.0, line: "En tus brazos, siempre en tus brazos" },
    { t: 99.5, line: "Uh, ah, uh, ah, uh-uh" },
    { t: 105.0, line: "Tu vientre y tu jacarandá" },
    { t: 110.5, line: "Incertidumbre y vanidad" },
    { t: 115.5, line: "Suerte y seducción" },
    { t: 119.5, line: "Soy tan vulnerable si te volteás" },
    { t: 123.5, line: "Amor de amores, casi incognitando mi cantar" },
    { t: 128.5, line: "Y aún no somos dos" },
    { t: 132.5, line: "Entre el bien y el mal hay una oración" },
    { t: 137.0, line: "Y dos pasos para atrás" },
    { t: 141.0, line: "¿Desde hace cuánto no sale el Sol?" },
    { t: 145.0, line: "Sé que el diablo blanco te consumió" },
    { t: 149.5, line: "Pero te quiero ver ser" },
    { t: 153.0, line: "En tus brazos, siento aquella flor" },
    { t: 157.0, line: "Marchitada de un jacarandá" },
    { t: 161.0, line: "Sos la diosa ama de mi Sol" },
    { t: 165.0, line: "Que me brinda luz en la oscuridad" },
    { t: 168.5, line: "En tus brazos, siempre en tus brazos" },
    { t: 171.5, line: "En tus brazos, siempre en tus brazos" }
  ];
})();